lesson_9, я не знаю что у меня за ошибка с дублированием и как ее заф…
eugene-okulik/mikalai.sud pull request #8
Opened 2024-12-10 22:56 UTC by Miksud

…иксить

2024-12-10 22:57 UTC, Miksud commented
странно что линт не ругается, у меня в 2.1 и 2.2 ругается на Duplicated code fragment (23 lines long), кароче не суть

2024-12-11 06:27 UTC, eugene-okulik commented
> странно что линт не ругается, у меня в 2.1 и 2.2 ругается на Duplicated code fragment (23 lines long), кароче не суть

Линт ругается обычно на оформление только, а не налогику.  
И да, у тебя 2.1 и 2.2 абсолютно одинаковые - один в один. Я не нашел отличий

2024-12-11 06:28 UTC, eugene-okulik requested changes
Второе задание должно быть выполнено с использованием map или filter (нужно понять что из этого здесь подходит). В выполнении не должно быть цикла.

2024-12-11 12:21 UTC, Miksud commented
Очень странно, но там действительно в двух файлах был одинаковый код :D видимо нечаянно натыкал что-то и он закопипастился в 2 файла, вопрос только куда делся мой код т.к я поискал его через ctrl + z и так и не нашел, its a magic

2024-12-12 06:44 UTC, merged